name: flutter_image_cropper
description: A Flutter plugin for image cropping functionality using native Android implementation
version: 0.1.0
homepage: https://github.com/yourusername/flutter_image_cropper

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.sml.flutter_image_cropper
        pluginClass: FlutterImageCropperPlugin